{"meta":{},
"id":"123",
"jobs":[
  {"meta":{},
    "id":"j1",
    "workflow":"123",
    "dependencies":[],
    "ready":false,
    "finished":false,
    "running":false,
    "waiting":false},
  {"meta":{},
    "id":"j2",
    "workflow":"123",
    "dependencies":[],
    "ready":false,
    "finished":false,
    "running":false,
    "waiting":false},
  {"meta":{},
    "id":"j3",
    "workflow":"123",
    "dependencies":[],
    "ready":false,
    "finished":false,
    "running":false,
    "waiting":false},
  {"meta":{},
"id":"j4",
"workflow":"123",
"dependencies":[],
"ready":false,
"finished":false,
"running":false,
"waiting":false}],
"resources":[{"meta":{},
"id":"r2",
"workflow":"123",
"pending":false,
"ready":false},
{"meta":{},
"id":"r3",
"workflow":"123",
"pending":false,
"ready":false},
{"meta":{},
"id":"r4",
"workflow":"123",
"pending":false,
"ready":false},
{"meta":{},
"id":"r1",
"workflow":"123",
"pending":false,
"ready":false}]}
